events {}

http {
    server {
        listen 80;

    location / {
            proxy_pass http://guacamole:8080/guacamole/;
            proxy_set_header Host $host;
            proxy_set_header X-Guacamole-Username guacadmin;
            proxy_set_header X-Guacamole-Password guacadmin;
        }
    }
}
