# Dockerfile.kali
FROM kalilinux/kali-rolling

ENV DEBIAN_FRONTEND=noninteractive
ENV USER=root

# Installation des outils et environnement graphique
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y \
    kali-linux-default \
    xfce4 xfce4-goodies \
    tightvncserver \
    xfonts-base \
    dbus-x11 \
    x11-xserver-utils \
    firefox-esr \
    burpsuite \
    wireshark \
    gobuster \
    hydra \
    sqlmap \
    john \
    net-tools iproute2 \
    sudo \
    openssh-server && \
    echo "root:toor" | chpasswd && \
    mkdir -p /var/run/sshd && \
    sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    mkdir -p /root/.vnc && \
    echo -e "#!/bin/bash\nxrdb $HOME/.Xresources\nstartxfce4 &" > /root/.vnc/xstartup && \
    chmod +x /root/.vnc/xstartup && \
    echo "toor" | vncpasswd -f > /root/.vnc/passwd && \
    chmod 600 /root/.vnc/passwd

EXPOSE 22
EXPOSE 5901

# CMD : démarre le serveur VNC + SSH
CMD /bin/bash -c "vncserver :1 -geometry 1280x720 -depth 24 && /usr/sbin/sshd -D"
