version: '3'

services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: always
    networks:
      att_net:

  guacamole-db:
    image: mysql:5.7
    container_name: guacamole-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacpass
    volumes:
      - ./guacamole/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./guacamole/02_admin.sql:/docker-entrypoint-initdb.d/02_admin.sql
    networks:
      att_net:

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: always
    depends_on:
      - guacd
      - guacamole-db
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacamole-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacpass
    ports:
      - "8888:8080"
    networks:
      att_net:

  kali:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: kali
    privileged: true
    restart: always
    ports:
      - "2222:22"
      - "5901:5901"
    tty: true
    dns:
      - 8.8.8.8
    networks:
      att_net:
        ipv4_address: 172.20.0.5

  win-auth-challenge1:
    build:
      context: ./vm_configs/windows-auth-challenge1
    container_name: win-auth-challenge1
    restart: always
    ports:
      - "2121:2121"
    networks:
      att_net:
        ipv4_address: 172.20.0.11

networks:
  att_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
