[global]
   workgroup = WORKGROUP
   server string = SMB Misconfig Challenge
   netbios name = WINSMB
   security = user
   map to guest = Bad User
   guest account = nobody
   smb ports = 445

   # 🔐 Protocole SMB2 minimum pour éviter les bugs de compatibilité
   min protocol = SMB2
   max protocol = SMB3

   # 🪵 Logging pour debug si besoin
   log level = 2
   log file = /var/log/samba.log

[WorkShares]
   path = /srv/smb/WorkShares
   browsable = yes
   writable = yes
   guest ok = yes
   read only = no
